
<Button>:
    background_color: (0,0,0,0)
    background_normal: ""
    pos_hint: {'center_x': 0.5}
    font_size: 30 if self.state == 'normal' else 25
    canvas.before:
        Color:
            rgba: [16/255, 16/255, 16/255,1] if self.state == 'normal' else [32/255, 32/255, 32/255,1]
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [50]

<Calc>:
    id: calc
    display_lb: display
    equate_to_lb: equate_to
    delete: delete
    BoxLayout:
        orientation: 'vertical'
        
        Label:
            id: display
            size_hint: 1, 0.3 
            font_size: 30
            markup: True
            text_size: self.size
            halign: 'right'
            color: 1,1,1,1
        
        Label:
            id: equate_to
            size_hint: 1, 0.2
            disabled: True
            font_size: 40
            text_size: self.size
            halign: 'right'
        
        Label:
            size_hint_y: 0.05
            canvas.before:
                Color:
                    rgba: (128/255, 128/255, 128/255,1)
                Line: 
                    width: 2.
                    points: (self.x, self.y+17, self.x+self.width, self.y+17)

        Button:
            id: delete
            pos_hint: {'x': 0.74}
            size_hint: 0.25, 0.2
            text: "undo"
            disabled: True
            on_release: root.backspace()

        
        GridLayout:
            cols: 4
            rows: 5
            spacing: 10, 10
            padding: 10, 10
            Button:
                text: "C"
                color: (252/255, 115/255, 3/255, 1)
                on_release: root.clear()
            Button:
                text: "( )"
                color: (0,1,0,1)
                on_release: root.brackets()
            Button:
                text: "π"
                color: (0,1,0,1)
                on_release: root.pi()
            Button: 
                text: "÷"
                color: (0,1,0,1)
                on_release: root.operation_selection("÷")
            Button:
                text: "7"
                on_release: root.numeric_selection(7)
            Button:
                text: "8"
                on_release: root.numeric_selection(8)
            Button: 
                text: "9"
                on_release: root.numeric_selection(9)
            Button:
                text: "X"
                color: (0,1,0,1)
                on_release: root.operation_selection("X")
            Button:
                text: "4"
                on_release: root.numeric_selection(4)
            Button: 
                text: "5"
                on_release: root.numeric_selection(5)
            Button:
                text: "6"
                on_release: root.numeric_selection(6)
            Button:
                text: "-"
                color: (0,1,0,1)
                on_release: root.operation_selection("-")
            Button: 
                text: "1"
                on_release: root.numeric_selection(1)
            Button:
                text: "2"
                on_release: root.numeric_selection(2)
            Button:
                text: "3"
                on_release: root.numeric_selection(3)
            Button: 
                text: "+"
                color: (0,1,0,1)
                on_release: root.operation_selection("+")
            Button:
                text: "+/-"
                on_release: root.negative_positive()
            Button:
                text: "0"
                on_release: root.numeric_selection(0)
            Button: 
                text: "."
                on_release: root.decimals()
            Button:
                text: "="
                color: (0,1,0,1)
                on_release: root.equals()
